LOAD DATA LOCAL INFILE 'C:\\laragon\\www\\exercice_sql\\vente.sql'
INTO TABLE vente
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(CODART,NUMFOU,DELLIV,QTE1,PRIX1,QTE2,PRIX2,QTE3,PRIX3);